In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
data =  pd.read_csv('../data/superstore.csv')
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

> Postal Code에 null값이 있다. 
1. Order ID(같은 주문을 묶어주므로)
2. Customer ID(동일인)

### Column 의미
- Sales: 판매액(단위: $)

In [5]:
data.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

In [6]:
data.drop(
    ['Row ID', 'Customer Name'],
    inplace=True,
    axis=1
)

data.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [7]:
print('Customer:',len(data['Customer ID'].value_counts()))
print('City:',len(data['City'].value_counts()))
print('State:',len(data['State'].value_counts()))
print('Product:',len(data['Product ID'].value_counts()))
print('Segment:',len(data['Segment'].value_counts()))
print('Ship Mode:',len(data['Ship Mode'].value_counts()))
print(len(data['Category'].value_counts()))
print(len(data['Sub-Category'].value_counts()))
# print(len(data['Sub-Category'].value_counts()))

Customer: 793
City: 529
State: 49
Product: 1861
Segment: 3
Ship Mode: 4
3
17

In [8]:
print('Category -> ',data['Category'].unique())
print()
print('Sub-Category -> ',data['Sub-Category'].unique())
print()
print('State -> ',data['State'].unique())
print()
print('Segment -> ',data['Segment'].unique())
print()
print('Region -> ',data['Region'].unique())
print()
print('Ship Mode -> ',data['Ship Mode'].unique())

Category ->  ['Furniture' 'Office Supplies' 'Technology']

Sub-Category ->  ['Bookcases' 'Chairs' 'Labels' 'Tables' 'Storage' 'Furnishings' 'Art'
 'Phones' 'Binders' 'Appliances' 'Paper' 'Accessories' 'Envelopes'
 'Fasteners' 'Supplies' 'Machines' 'Copiers']

State ->  ['Kentucky' 'California' 'Florida' 'North Carolina' 'Washington' 'Texas'
 'Wisconsin' 'Utah' 'Nebraska' 'Pennsylvania' 'Illinois' 'Minnesota'
 'Michigan' 'Delaware' 'Indiana' 'New York' 'Arizona' 'Virginia'
 'Tennessee' 'Alabama' 'South Carolina' 'Oregon' 'Colorado' 'Iowa' 'Ohio'
 'Missouri' 'Oklahoma' 'New Mexico' 'Louisiana' 'Connecticut' 'New Jersey'
 'Massachusetts' 'Georgia' 'Nevada' 'Rhode Island' 'Mississippi'
 'Arkansas' 'Montana' 'New Hampshire' 'Maryland' 'District of Columbia'
 'Kansas' 'Vermont' 'Maine' 'South Dakota' 'Idaho' 'North Dakota'
 'Wyoming' 'West Virginia']

Segment ->  ['Consumer' 'Corporate' 'Home Office']

Region ->  ['South' 'West' 'Central' 'East']

Ship Mode ->  ['Second Class' 'Standard Class' 'First Class' 'Same Day']

> 미국은 총 50개의 State로 이루어져 있는데, 지리적으로 멀리 떨어진 알래스카와 하와이는 배송 목록에 없으며,  
Washington D.C.가 Washington과 District of Columbia 2가지로 표시되어 있다.

> District of Columbia -> Washington으로 변경하기

> **고객 종류**
- Consumer: 일반 고객
- Corporate: 법인 고객
- Home Office: 소규모 사업자?

In [9]:
pivot_table = data.pivot_table(
    index=['Customer ID','Order ID','Order Date','Ship Date','Postal Code'],     
    columns=['Segment'], 
    values='Sales',
    aggfunc='sum',
)

pivot_table.head(50)

Segment                                                       Consumer  \
Customer ID Order ID       Order Date Ship Date  Postal Code
AA-10315    CA-2015-128055 31/03/2015 05/04/2015 94122.0       726.548
            CA-2015-138100 15/09/2015 20/09/2015 10011.0        29.500
            CA-2016-121391 04/10/2016 07/10/2016 94109.0        26.960
            CA-2017-103982 03/03/2017 08/03/2017 78664.0      4406.072
            CA-2018-147039 29/06/2018 04/07/2018 55407.0       374.480
AA-10375    CA-2015-130729 24/10/2015 29/10/2015 91730.0        34.272
            CA-2015-158064 21/04/2015 25/04/2015 90008.0        16.520
            CA-2016-109939 08/05/2016 12/05/2016 97301.0         5.248
            CA-2016-114503 13/11/2016 17/11/2016 37087.0        84.960
            CA-2016-140921 03/02/2016 05/02/2016 68104.0       178.370
            CA-2017-126613 10/07/2017 16/07/2017 85204.0        16.768
            CA-2017-131065 14/11/2017 16/11/2017 30318.0       513.520
            CA-2018-100230 11/12/2018 15/12/2018 10035.0       149.872
            US-2018-169488 07/09/2018 09/09/2018 2908.0         56.860
AA-10480    CA-2015-155271 04/05/2015 04/05/2015 6457.0         27.460
            CA-2017-114601 26/08/2017 02/09/2017 48234.0      1157.980
            CA-2017-121671 17/07/2017 22/07/2017 65807.0       589.520
            CA-2018-114412 15/04/2018 20/04/2018 28027.0        15.552
AA-10645    CA-2015-143210 01/12/2015 03/12/2015 1852.0        327.560
            CA-2015-154963 22/06/2015 27/06/2015 19013.0      1106.770
            CA-2016-110863 17/11/2016 24/11/2016 73120.0      1971.460
            CA-2017-131205 04/09/2017 08/09/2017 40324.0       291.740
            CA-2017-147137 04/07/2017 06/07/2017 94109.0      1376.445
            CA-2018-157196 05/11/2018 09/11/2018 92105.0        12.960
AB-10015    CA-2015-152905 18/02/2015 24/02/2015 76017.0        12.624
            CA-2015-156587 07/03/2015 08/03/2015 98103.0       309.592
            CA-2017-140935 10/11/2017 12/11/2017 73120.0       563.940
AB-10060    CA-2016-150511 18/09/2016 24/09/2016 98198.0           NaN
            CA-2017-129714 01/09/2017 03/09/2017 10009.0           NaN
            CA-2017-161207 29/08/2017 03/09/2017 3301.0            NaN
            CA-2018-107174 06/11/2018 13/11/2018 98105.0           NaN
            CA-2018-118213 05/11/2018 07/11/2018 46142.0           NaN
            CA-2018-134173 16/09/2018 21/09/2018 19143.0           NaN
            CA-2018-159688 07/05/2018 12/05/2018 90004.0           NaN
            US-2017-108637 13/03/2017 18/03/2017 22980.0           NaN
AB-10105    CA-2015-103100 20/12/2015 23/12/2015 46203.0      1107.660
            CA-2016-163181 07/11/2016 12/11/2016 77041.0       671.002
            CA-2017-117121 17/12/2017 21/12/2017 48205.0      9892.740
            CA-2017-147431 02/02/2017 07/02/2017 10011.0       117.960
            CA-2018-101042 19/11/2018 23/11/2018 42420.0       843.840
            CA-2018-121643 18/05/2018 20/05/2018 97206.0       344.704
            CA-2018-126788 05/06/2018 06/06/2018 77581.0       470.376
            CA-2018-140781 03/08/2018 07/08/2018 61701.0        39.816
            CA-2018-153822 19/09/2018 25/09/2018 85023.0       592.308
            US-2017-122245 25/09/2017 30/09/2017 85023.0       393.165
AB-10150    CA-2015-169061 05/03/2015 08/03/2015 10701.0       705.562
            CA-2016-168186 10/09/2016 15/09/2016 74133.0        14.940
            CA-2017-147970 31/01/2017 02/02/2017 75220.0        15.552
            CA-2018-120761 04/09/2018 08/09/2018 11561.0        91.960
            CA-2018-158876 19/11/2018 21/11/2018 75007.0       138.696

Segment                                                       Corporate  \
Customer ID Order ID       Order Date Ship Date  Postal Code
AA-10315    CA-2015-128055 31/03/2015 05/04/2015 94122.0            NaN
            CA-2015-138100 15/09/2015 20/09/2015 10011.0            NaN
            CA-2016-121391 04/10/2016 07/10/2016 94109.0            NaN
            CA-2017-103982 03/03/2017 08/03/2017 78664.0            NaN
            CA-2018-147039 29/06/2018 04/07/2018 55407.0            NaN
AA-10375    CA-2015-130729 24/10/2015 29/10/2015 91730.0            NaN
            CA-2015-158064 21/04/2015 25/04/2015 90008.0            NaN
            CA-2016-109939 08/05/2016 12/05/2016 97301.0            NaN
            CA-2016-114503 13/11/2016 17/11/2016 37087.0            NaN
            CA-2016-140921 03/02/2016 05/02/2016 68104.0            NaN
            CA-2017-126613 10/07/2017 16/07/2017 85204.0            NaN
            CA-2017-131065 14/11/2017 16/11/2017 30318.0            NaN
            CA-2018-100230 11/12/2018 15/12/2018 10035.0            NaN
            US-2018-169488 07/09/2018 09/09/2018 2908.0             NaN
AA-10480    CA-2015-155271 04/05/2015 04/05/2015 6457.0             NaN
            CA-2017-114601 26/08/2017 02/09/2017 48234.0            NaN
            CA-2017-121671 17/07/2017 22/07/2017 65807.0            NaN
            CA-2018-114412 15/04/2018 20/04/2018 28027.0            NaN
AA-10645    CA-2015-143210 01/12/2015 03/12/2015 1852.0             NaN
            CA-2015-154963 22/06/2015 27/06/2015 19013.0            NaN
            CA-2016-110863 17/11/2016 24/11/2016 73120.0            NaN
            CA-2017-131205 04/09/2017 08/09/2017 40324.0            NaN
            CA-2017-147137 04/07/2017 06/07/2017 94109.0            NaN
            CA-2018-157196 05/11/2018 09/11/2018 92105.0            NaN
AB-10015    CA-2015-152905 18/02/2015 24/02/2015 76017.0            NaN
            CA-2015-156587 07/03/2015 08/03/2015 98103.0            NaN
            CA-2017-140935 10/11/2017 12/11/2017 73120.0            NaN
AB-10060    CA-2016-150511 18/09/2016 24/09/2016 98198.0            NaN
            CA-2017-129714 01/09/2017 03/09/2017 10009.0            NaN
            CA-2017-161207 29/08/2017 03/09/2017 3301.0             NaN
            CA-2018-107174 06/11/2018 13/11/2018 98105.0            NaN
            CA-2018-118213 05/11/2018 07/11/2018 46142.0            NaN
            CA-2018-134173 16/09/2018 21/09/2018 19143.0            NaN
            CA-2018-159688 07/05/2018 12/05/2018 90004.0            NaN
            US-2017-108637 13/03/2017 18/03/2017 22980.0            NaN
AB-10105    CA-2015-103100 20/12/2015 23/12/2015 46203.0            NaN
            CA-2016-163181 07/11/2016 12/11/2016 77041.0            NaN
            CA-2017-117121 17/12/2017 21/12/2017 48205.0            NaN
            CA-2017-147431 02/02/2017 07/02/2017 10011.0            NaN
            CA-2018-101042 19/11/2018 23/11/2018 42420.0            NaN
            CA-2018-121643 18/05/2018 20/05/2018 97206.0            NaN
            CA-2018-126788 05/06/2018 06/06/2018 77581.0            NaN
            CA-2018-140781 03/08/2018 07/08/2018 61701.0            NaN
            CA-2018-153822 19/09/2018 25/09/2018 85023.0            NaN
            US-2017-122245 25/09/2017 30/09/2017 85023.0            NaN
AB-10150    CA-2015-169061 05/03/2015 08/03/2015 10701.0            NaN
            CA-2016-168186 10/09/2016 15/09/2016 74133.0            NaN
            CA-2017-147970 31/01/2017 02/02/2017 75220.0            NaN
            CA-2018-120761 04/09/2018 08/09/2018 11561.0            NaN
            CA-2018-158876 19/11/2018 21/11/2018 75007.0            NaN

Segment                                                       Home Office
Customer ID Order ID       Order Date Ship Date  Postal Code
AA-10315    CA-2015-128055 31/03/2015 05/04/2015 94122.0              NaN
            CA-2015-138100 15/09/2015 20/09/2015 10011.0              NaN
            CA-2016-121391 04/10/2016 07/10/2016 94109.0              NaN
            CA-2017-103982 03/03/2017 08/03/2017 78664.0              NaN
            CA-2018-147039 29/06/2018 04/07/2018 55407.0              NaN
AA-10375    CA-2015-130729 24/10/2015 29/10/2015 91730.0              NaN
            CA-2015-158064 21/04/2015 25/04/2015 90008.0              NaN
            CA-2016-109939 08/05/2016 12/05/2016 97301.0              NaN
            CA-2016-114503 13/11/2016 17/11/2016 37087.0              NaN
            CA-2016-140921 03/02/2016 05/02/2016 68104.0              NaN
            CA-2017-126613 10/07/2017 16/07/2017 85204.0              NaN
            CA-2017-131065 14/11/2017 16/11/2017 30318.0              NaN
            CA-2018-100230 11/12/2018 15/12/2018 10035.0              NaN
            US-2018-169488 07/09/2018 09/09/2018 2908.0               NaN
AA-10480    CA-2015-155271 04/05/2015 04/05/2015 6457.0               NaN
            CA-2017-114601 26/08/2017 02/09/2017 48234.0              NaN
            CA-2017-121671 17/07/2017 22/07/2017 65807.0              NaN
            CA-2018-114412 15/04/2018 20/04/2018 28027.0              NaN
AA-10645    CA-2015-143210 01/12/2015 03/12/2015 1852.0               NaN
            CA-2015-154963 22/06/2015 27/06/2015 19013.0              NaN
            CA-2016-110863 17/11/2016 24/11/2016 73120.0              NaN
            CA-2017-131205 04/09/2017 08/09/2017 40324.0              NaN
            CA-2017-147137 04/07/2017 06/07/2017 94109.0              NaN
            CA-2018-157196 05/11/2018 09/11/2018 92105.0              NaN
AB-10015    CA-2015-152905 18/02/2015 24/02/2015 76017.0              NaN
            CA-2015-156587 07/03/2015 08/03/2015 98103.0              NaN
            CA-2017-140935 10/11/2017 12/11/2017 73120.0              NaN
AB-10060    CA-2016-150511 18/09/2016 24/09/2016 98198.0           18.540
            CA-2017-129714 01/09/2017 03/09/2017 10009.0         4438.686
            CA-2017-161207 29/08/2017 03/09/2017 3301.0            27.930
            CA-2018-107174 06/11/2018 13/11/2018 98105.0         2595.388
            CA-2018-118213 05/11/2018 07/11/2018 46142.0          240.150
            CA-2018-134173 16/09/2018 21/09/2018 19143.0           20.736
            CA-2018-159688 07/05/2018 12/05/2018 90004.0           79.990
            US-2017-108637 13/03/2017 18/03/2017 22980.0          334.200
AB-10105    CA-2015-103100 20/12/2015 23/12/2015 46203.0              NaN
            CA-2016-163181 07/11/2016 12/11/2016 77041.0              NaN
            CA-2017-117121 17/12/2017 21/12/2017 48205.0              NaN
            CA-2017-147431 02/02/2017 07/02/2017 10011.0              NaN
            CA-2018-101042 19/11/2018 23/11/2018 42420.0              NaN
            CA-2018-121643 18/05/2018 20/05/2018 97206.0              NaN
            CA-2018-126788 05/06/2018 06/06/2018 77581.0              NaN
            CA-2018-140781 03/08/2018 07/08/2018 61701.0              NaN
            CA-2018-153822 19/09/2018 25/09/2018 85023.0              NaN
            US-2017-122245 25/09/2017 30/09/2017 85023.0              NaN
AB-10150    CA-2015-169061 05/03/2015 08/03/2015 10701.0              NaN
            CA-2016-168186 10/09/2016 15/09/2016 74133.0              NaN
            CA-2017-147970 31/01/2017 02/02/2017 75220.0              NaN
            CA-2018-120761 04/09/2018 08/09/2018 11561.0              NaN
            CA-2018-158876 19/11/2018 21/11/2018 75007.0              NaN

In [10]:
import pandas as pd

def calculate_shipping_duration(df):
    # 'Order Date'와 'Ship Date' 열을 datetime 형식으로 변환
    df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
    df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)
    
    # 두 날짜의 차이를 계산하여 새로운 열 'Shipping Duration'에 저장
    df['Shipping Duration'] = (df['Ship Date'] - df['Order Date']).dt.days
    
    return df

In [11]:
calculate_shipping_duration(data)

data.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Shipping Duration
0,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3
2,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4
3,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,7
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,7

> 각 Region(South, West, East, Central)별로 City unique 확인하기

In [12]:
data.head(20)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Shipping Duration
0,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3
2,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4
3,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,7
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,7
5,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,5
6,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,5
7,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,5
8,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Consumer,United States,Los Angeles,California,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,5
9,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5
10,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Consumer,United States,Los Angeles,California,90032.0,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,5
11,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240,5
12,CA-2018-114412,2018-04-15,2018-04-20,Standard Class,AA-10480,Consumer,United States,Concord,North Carolina,28027.0,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.5520,5
13,CA-2017-161389,2017-12-05,2017-12-10,Standard Class,IM-15070,Consumer,United States,Seattle,Washington,98103.0,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760,5
14,US-2016-118983,2016-11-22,2016-11-26,Standard Class,HP-14815,Home Office,United States,Fort Worth,Texas,76106.0,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,4
15,US-2016-118983,2016-11-22,2016-11-26,Standard Class,HP-14815,Home Office,United States,Fort Worth,Texas,76106.0,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,4
16,CA-2015-105893,2015-11-11,2015-11-18,Standard Class,PK-19075,Consumer,United States,Madison,Wisconsin,53711.0,Central,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.8800,7
17,CA-2015-167164,2015-05-13,2015-05-15,Second Class,AG-10270,Consumer,United States,West Jordan,Utah,84084.0,West,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.5000,2
18,CA-2015-143336,2015-08-27,2015-09-01,Second Class,ZD-21925,Consumer,United States,San Francisco,California,94109.0,West,OFF-AR-10003056,Office Supplies,Art,Newell 341,8.5600,5
19,CA-2015-143336,2015-08-27,2015-09-01,Second Class,ZD-21925,Consumer,United States,San Francisco,California,94109.0,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.4800,5

In [13]:
data[data['Ship Mode']=='Same Day'].head(20)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Shipping Duration
366,CA-2017-155516,2017-10-21,2017-10-21,Same Day,MK-17905,Corporate,United States,Manchester,Connecticut,6040.0,East,OFF-BI-10002412,Office Supplies,Binders,Wilson Jones “Snap” Scratch Pad Binder Tool fo...,23.200,0
367,CA-2017-155516,2017-10-21,2017-10-21,Same Day,MK-17905,Corporate,United States,Manchester,Connecticut,6040.0,East,OFF-SU-10001225,Office Supplies,Supplies,Staple remover,7.360,0
368,CA-2017-155516,2017-10-21,2017-10-21,Same Day,MK-17905,Corporate,United States,Manchester,Connecticut,6040.0,East,OFF-ST-10002406,Office Supplies,Storage,Pizazz Global Quick File,104.790,0
369,CA-2017-155516,2017-10-21,2017-10-21,Same Day,MK-17905,Corporate,United States,Manchester,Connecticut,6040.0,East,FUR-BO-10002545,Furniture,Bookcases,"Atlantic Metals Mobile 3-Shelf Bookcases, Cust...",1043.920,0
657,US-2017-156097,2017-09-19,2017-09-19,Same Day,EH-14125,Home Office,United States,Aurora,Illinois,60505.0,Central,FUR-CH-10001215,Furniture,Chairs,Global Troy Executive Leather Low-Back Tilter,701.372,0
658,US-2017-156097,2017-09-19,2017-09-19,Same Day,EH-14125,Home Office,United States,Aurora,Illinois,60505.0,Central,OFF-BI-10004654,Office Supplies,Binders,Avery Binding System Hidden Tab Executive Styl...,2.308,0
664,CA-2017-143308,2017-11-04,2017-11-04,Same Day,RC-19825,Consumer,United States,Louisville,Kentucky,40214.0,South,OFF-FA-10000621,Office Supplies,Fasteners,"OIC Colored Binder Clips, Assorted Sizes",10.740,0
683,US-2018-168116,2018-11-04,2018-11-04,Same Day,GT-14635,Corporate,United States,Burlington,North Carolina,27217.0,South,TEC-MA-10004125,Technology,Machines,Cubify CubeX 3D Printer Triple Head Print,7999.980,0
684,US-2018-168116,2018-11-04,2018-11-04,Same Day,GT-14635,Corporate,United States,Burlington,North Carolina,27217.0,South,OFF-AP-10002457,Office Supplies,Appliances,Eureka The Boss Plus 12-Amp Hard Box Upright V...,167.440,0
746,CA-2015-124429,2015-05-27,2015-05-27,Same Day,MH-17785,Corporate,United States,San Diego,California,92105.0,West,FUR-TA-10002607,Furniture,Tables,KI Conference Tables,567.120,0
747,CA-2015-124429,2015-05-27,2015-05-27,Same Day,MH-17785,Corporate,United States,San Diego,California,92105.0,West,OFF-ST-10001809,Office Supplies,Storage,Fellowes Officeware Wire Shelving,359.320,0
792,CA-2017-105256,2017-05-20,2017-05-20,Same Day,JK-15730,Consumer,United States,Asheville,North Carolina,28806.0,South,TEC-PH-10001530,Technology,Phones,Cisco Unified IP Phone 7945G VoIP phone,1363.960,0
813,CA-2018-143686,2018-05-14,2018-05-14,Same Day,PJ-19015,Consumer,United States,Santa Ana,California,92704.0,West,FUR-FU-10000794,Furniture,Furnishings,"Eldon Stackable Tray, Side-Load, Legal, Smoke",18.280,0
814,CA-2018-143686,2018-05-14,2018-05-14,Same Day,PJ-19015,Consumer,United States,Santa Ana,California,92704.0,West,TEC-AC-10001838,Technology,Accessories,Razer Tiamat Over Ear 7.1 Surround Sound PC Ga...,1399.930,0
882,US-2018-123463,2018-12-23,2018-12-23,Same Day,GZ-14470,Consumer,United States,San Francisco,California,94109.0,West,OFF-AR-10001118,Office Supplies,Art,"Binney & Smith Crayola Metallic Crayons, 16-Co...",13.480,0
959,CA-2016-112571,2016-09-22,2016-09-22,Same Day,DL-12925,Consumer,United States,Oceanside,California,92054.0,West,FUR-FU-10004188,Furniture,Furnishings,Luxo Professional Combination Clamp-On Lamps,204.600,0
987,CA-2016-146829,2016-03-10,2016-03-10,Same Day,TS-21340,Consumer,United States,Houston,Texas,77041.0,Central,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,1.112,0
1001,CA-2016-124891,2016-07-31,2016-07-31,Same Day,RH-19495,Consumer,United States,New York City,New York,10024.0,East,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,0
1002,CA-2016-124891,2016-07-31,2016-07-31,Same Day,RH-19495,Consumer,United States,New York City,New York,10024.0,East,FUR-TA-10002903,Furniture,Tables,"Bevis Round Bullnose 29"" High Table Top",1090.782,0
1003,CA-2016-124891,2016-07-31,2016-07-31,Same Day,RH-19495,Consumer,United States,New York City,New York,10024.0,East,OFF-PA-10004621,Office Supplies,Paper,Xerox 212,19.440,0

In [ ]:
data.loc[data['Ship Mode']=='Same Day','Ship Mode'].mean()

In [14]:
print(data['Order Date'].max())
print(data['Order Date'].min())

2018-12-30 00:00:00
2015-01-03 00:00:00

> 2015 ~ 2018 **4개년** data

---
### hub 위치 정하기

In [15]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [21]:
standardShip = data[data['Ship Mode']=='Standard Class']

In [20]:
clustering_data = data[['Shipping Duration', 'Latitude', 'Longitude']].dropna()

kmeans = KMeans(n_clusters=5, random_state=42)
clustering_data['Cluster'] = kmeans.fit_predict(clustering_data)

클러스터 중심:
[[5.6103764 ]
 [2.43026837]
 [0.41391106]
 [4.        ]]

In [ ]:
# !pip3 install uszipcode

In [28]:
# !pip3 install zipcodes

Collecting zipcodes
  Downloading zipcodes-1.2.0-py2.py3-none-any.whl.metadata (7.4 kB)
Downloading zipcodes-1.2.0-py2.py3-none-any.whl (719 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 719.6/719.6 kB 13.7 MB/s eta 0:00:00a 0:00:01
Installing collected packages: zipcodes
Successfully installed zipcodes-1.2.0

In [26]:
# !pip3 install 'sqlalchemy_mate<2.0.0.1'

Collecting sqlalchemy_mate<2.0.0.1
  Downloading sqlalchemy_mate-2.0.0.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy<3.0.0,>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy_mate<2.0.0.1) (2.0.30)
Requirement already satisfied: prettytable<4.0.0,>=3.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy_mate<2.0.0.1) (3.12.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.12/site-packages (from prettytable<4.0.0,>=3.0.0->sqlalchemy_mate<2.0.0.1) (0.2.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy<3.0.0,>=2.0.0->sqlalchemy_mate<2.0.0.1) (4.12.2)
Downloading sqlalchemy_mate-2.0.0.0-py3-none-any.whl (36 kB)
Installing collected packages: sqlalchemy_mate
  Attempting uninstall: sqlalchemy_mate
    Found existing installation: sqlalchemy_mate 2.0.0.3
    Uninstalling sqlalchemy_mate-2.0.0.3:
      Successfully uninstalled sqlalchemy_mate-2.0.0.3
Successfully installed sqlalchemy_mate-2.0.0.0

In [32]:
# !pip3 install sqlalchemy_mate

Requirement already satisfied: sqlalchemy_mate in /opt/anaconda3/lib/python3.12/site-packages (2.0.0.0)
Requirement already satisfied: sqlalchemy<3.0.0,>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy_mate) (2.0.30)
Requirement already satisfied: prettytable<4.0.0,>=3.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy_mate) (3.12.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.12/site-packages (from prettytable<4.0.0,>=3.0.0->sqlalchemy_mate) (0.2.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy<3.0.0,>=2.0.0->sqlalchemy_mate) (4.12.2)

In [34]:
# !pip3 install --upgrade sqlalchemy_mate

Requirement already satisfied: sqlalchemy_mate in /opt/anaconda3/lib/python3.12/site-packages (2.0.0.0)
Collecting sqlalchemy_mate
  Using cached sqlalchemy_mate-2.0.0.3-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy<3.0.0,>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy_mate) (2.0.30)
Requirement already satisfied: prettytable<4.0.0,>=3.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy_mate) (3.12.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.12/site-packages (from prettytable<4.0.0,>=3.0.0->sqlalchemy_mate) (0.2.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy<3.0.0,>=2.0.0->sqlalchemy_mate) (4.12.2)
Using cached sqlalchemy_mate-2.0.0.3-py3-none-any.whl (59 kB)
Installing collected packages: sqlalchemy_mate
  Attempting uninstall: sqlalchemy_mate
    Found existing installation: sqlalchemy_mate 2.0.0.0
    Uninstalling sqlalchemy_mate-2.0.0.0:
      Successfully uninstalled sqlalchemy_mate-2.0.0.0
Successfully installed sqlalchemy_mate-2.0.0.3

In [37]:
# from sqlalchemy_mate.api import ExtendedBase

In [ ]:
# from uszipcode import SearchEngine

# def get_lat_long(zipcode):
#     search = SearchEngine()
#     result = search.by_zipcode(zipcode)
#     if result:
#         return result.lat, result.lng
#     return None, None

# # 데이터프레임의 'Postal Code' column을 이용하여 위도/경도 추가
# data['lat'], data['lng'] = zip(*data['Postal Code'].apply(get_lat_long))

In [39]:
# !pip3 install geopy

Collecting geopy
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.0-py3-none-any.whl.metadata (1.4 kB)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.4/125.4 kB 5.6 MB/s eta 0:00:00
Downloading geographiclib-2.0-py3-none-any.whl (40 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 kB 4.8 MB/s eta 0:00:00
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.0 geopy-2.4.1

In [ ]:
# from geopy.geocoders import Nominatim
# from geopy.exc import GeocoderTimedOut, GeocoderServiceError

# # Nominatim 초기화
# geolocator = Nominatim(user_agent="myGeocoder")

# def get_lat_lon(postal_code):
#     try:
#         location = geolocator.geocode(f"{postal_code}, USA")
#         if location:
#             return location.latitude, location.longitude
#         return None, None
#     except (GeocoderTimedOut, GeocoderServiceError):
#         return None, None

# # 위도와 경도 열 추가
# data['lat'], data['lng'] = zip(*data['Postal Code'].apply(get_lat_lon))

# # 결과 확인
# print(data[['Postal Code', 'lat', 'lng']].head())

In [54]:
location = pd.read_csv('../data/US_zipcode.csv')
location = location.iloc[:,[0, 3]]
location.head()

   ZCTA Code                                       centroid
0      31021   POINT (-82.93582571874998 32.36283290624999)
1      82730  POINT (-104.72272443164064 44.02357945507812)
2      99726   POINT (-151.9585490087891 66.91762888378904)
3      99689                  POINT (-139.503972 59.701155)
4      31568  POINT (-81.84550492968748 31.014587539062504)

In [55]:
location.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33144 entries, 0 to 33143
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ZCTA Code  33144 non-null  int64
 1   centroid   33144 non-null  object
dtypes: int64(1), object(1)
memory usage: 518.0+ KB

In [56]:
location[location['ZCTA Code']==6040]

       ZCTA Code                                      centroid
11953       6040  POINT (-72.54779593749998 41.75880693749999)

In [57]:
def extract_coordinates(point):
    # 'POINT (' 와 ')' 제거 후 공백으로 분리
    coords = point.replace('POINT (', '').replace(')', '').split()
    return pd.Series({'lng': float(coords[0]), 'lat': float(coords[1])})

# 함수 적용하여 새로운 열 생성
location[['lng', 'lat']] = location['centroid'].apply(extract_coordinates)

In [58]:
location.head()

,ZCTA Code,centroid,lng,lat
0,31021,POINT (-82.93582571874998 32.36283290624999),-82.935826,32.362833
1,82730,POINT (-104.72272443164064 44.02357945507812),-104.722724,44.023579
2,99726,POINT (-151.9585490087891 66.91762888378904),-151.958549,66.917629
3,99689,POINT (-139.503972 59.701155),-139.503972,59.701155
4,31568,POINT (-81.84550492968748 31.014587539062504),-81.845505,31.014588

In [59]:
location.drop(
    'centroid',
    axis=1,
    inplace=True
)
location.head()

   ZCTA Code         lng        lat
0      31021  -82.935826  32.362833
1      82730 -104.722724  44.023579
2      99726 -151.958549  66.917629
3      99689 -139.503972  59.701155
4      31568  -81.845505  31.014588

In [60]:
location.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33144 entries, 0 to 33143
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ZCTA Code  33144 non-null  int64
 1   lng        33144 non-null  float64
 2   lat        33144 non-null  float64
dtypes: float64(2), int64(1)
memory usage: 776.9 KB

---
### Postal Code 결측치 처리
1. Order ID
2. Customer ID
3. Drop

> Order ID가 같은 것으로 결측치 대체

In [62]:
# Order ID를 기준으로 Postal Code의 딕셔너리 생성 (결측치 제외)
order_id_to_postal_code = data.dropna(subset=['Postal Code']).groupby('Order ID')['Postal Code'].first().to_dict()

# 결측치를 딕셔너리를 이용해 채우기
data['Postal Code'] = data.apply(
    lambda row: order_id_to_postal_code.get(row['Order ID'], row['Postal Code']) 
    if pd.isnull(row['Postal Code']) else row['Postal Code'],
    axis=1
)

In [63]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           9800 non-null   object
 1   Order Date         9800 non-null   datetime64[ns]
 2   Ship Date          9800 non-null   datetime64[ns]
 3   Ship Mode          9800 non-null   object
 4   Customer ID        9800 non-null   object
 5   Segment            9800 non-null   object
 6   Country            9800 non-null   object
 7   City               9800 non-null   object
 8   State              9800 non-null   object
 9   Postal Code        9789 non-null   float64
 10  Region             9800 non-null   object
 11  Product ID         9800 non-null   object
 12  Category           9800 non-null   object
 13  Sub-Category       9800 non-null   object
 14  Product Name       9800 non-null   object
 15  Sales              9800 non-null   float64
 16  Shipping Duration  9800 non-null   int64
 17  Cluster            9800 non-null   int32
dtypes: datetime64[ns](2), float64(2), int32(1), int64(1), object(12)
memory usage: 1.3+ MB

> Order ID 기준으로는 결측치가 채워지지 않았다.

> Customer ID가 같은 것으로 결측치 대체

In [64]:
# Customer ID를 기준으로 Postal Code의 딕셔너리 생성 (결측치 제외)
order_id_to_postal_code = data.dropna(subset=['Postal Code']).groupby('Customer ID')['Postal Code'].first().to_dict()

# 결측치를 딕셔너리를 이용해 채우기
data['Postal Code'] = data.apply(
    lambda row: order_id_to_postal_code.get(row['Customer ID'], row['Postal Code']) 
    if pd.isnull(row['Postal Code']) else row['Postal Code'],
    axis=1
)

In [65]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           9800 non-null   object
 1   Order Date         9800 non-null   datetime64[ns]
 2   Ship Date          9800 non-null   datetime64[ns]
 3   Ship Mode          9800 non-null   object
 4   Customer ID        9800 non-null   object
 5   Segment            9800 non-null   object
 6   Country            9800 non-null   object
 7   City               9800 non-null   object
 8   State              9800 non-null   object
 9   Postal Code        9800 non-null   float64
 10  Region             9800 non-null   object
 11  Product ID         9800 non-null   object
 12  Category           9800 non-null   object
 13  Sub-Category       9800 non-null   object
 14  Product Name       9800 non-null   object
 15  Sales              9800 non-null   float64
 16  Shipping Duration  9800 non-null   int64
 17  Cluster            9800 non-null   int32
dtypes: datetime64[ns](2), float64(2), int32(1), int64(1), object(12)
memory usage: 1.3+ MB

> Customer ID가 같은 기준으로 결측치가 모두 채워졌다.

In [69]:
data['Postal Code'] = data['Postal Code'].astype('int64')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           9800 non-null   object
 1   Order Date         9800 non-null   datetime64[ns]
 2   Ship Date          9800 non-null   datetime64[ns]
 3   Ship Mode          9800 non-null   object
 4   Customer ID        9800 non-null   object
 5   Segment            9800 non-null   object
 6   Country            9800 non-null   object
 7   City               9800 non-null   object
 8   State              9800 non-null   object
 9   Postal Code        9800 non-null   int64
 10  Region             9800 non-null   object
 11  Product ID         9800 non-null   object
 12  Category           9800 non-null   object
 13  Sub-Category       9800 non-null   object
 14  Product Name       9800 non-null   object
 15  Sales              9800 non-null   float64
 16  Shipping Duration  9800 non-null   int64
 17  Cluster            9800 non-null   int32
dtypes: datetime64[ns](2), float64(1), int32(1), int64(2), object(12)
memory usage: 1.3+ MB

In [70]:
data.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Shipping Duration,Cluster
0,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3,1
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,1
2,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,3
3,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,7,0
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,7,0

In [ ]:
data.drop(
    'Cluster',
    axis=1,
    inplace=True
)
# data.head()

In [72]:
data_merge = pd.merge(data, location,
                    how='left', left_on='Postal Code', right_on='ZCTA Code')
data_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           9800 non-null   object
 1   Order Date         9800 non-null   datetime64[ns]
 2   Ship Date          9800 non-null   datetime64[ns]
 3   Ship Mode          9800 non-null   object
 4   Customer ID        9800 non-null   object
 5   Segment            9800 non-null   object
 6   Country            9800 non-null   object
 7   City               9800 non-null   object
 8   State              9800 non-null   object
 9   Postal Code        9800 non-null   int64
 10  Region             9800 non-null   object
 11  Product ID         9800 non-null   object
 12  Category           9800 non-null   object
 13  Sub-Category       9800 non-null   object
 14  Product Name       9800 non-null   object
 15  Sales              9800 non-null   float64
 16  Shipping Duration  9800 non-null   int64
 17  ZCTA Code          9800 non-null   int64
 18  lng                9800 non-null   float64
 19  lat                9800 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(12)
memory usage: 1.5+ MB

In [74]:
data_merge.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Shipping Duration,ZCTA Code,lng,lat
0,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3,42420,-87.533344,37.815369
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,42420,-87.533344,37.815369
2,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,90036,-118.349755,34.069966
3,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,7,33311,-80.165442,26.145383
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,7,33311,-80.165442,26.145383

> Product ID: Category와 Sub-Category 정보 모두 포함하고 있다.

In [75]:
data_merge.drop(
    'ZCTA Code',
    axis=1,
    inplace=True
)

In [76]:
data_merge.to_csv('../data/super_loc.csv',index=False)
check = pd.read_csv('../data/super_loc.csv')
check.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Shipping Duration,lng,lat
0,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3,-87.533344,37.815369
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,-87.533344,37.815369
2,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,-118.349755,34.069966
3,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,7,-80.165442,26.145383
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,7,-80.165442,26.145383